package com.tablehockey.game.game

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.os.Handler
import android.os.Looper
import com.tablehockey.game.R
import com.tablehockey.game.model.ArenaType
import java.util.concurrent.ConcurrentHashMap
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.exp
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin
import kotlin.random.Random

/**
 * All in-match effects: puck, boards, posts, hits, saves, whistle, horn,
 * crowd, skate scrapes, the arena organ and the 8-bit jingles. Every sample
 * is generated by tools/make_sounds.py.
 *
 * Beyond plain playback it does a little live mixing:
 *  - variants: shots, passes, boards, hits, saves and strides each have
 *    several takes, rotated so the same one never plays twice running;
 *  - stereo: puck sounds are panned by where the puck is on screen;
 *  - intensity: harder shots and passes play louder and slightly brighter;
 *  - a crowd that reacts: a murmur loop plus a roar loop that swells with an
 *    excitement level driven by events and by the puck nearing a net;
 *  - arena: indoors, big impacts get a short reverb tail; the outdoor pond
 *    swaps the crowd for wind, skips the organ and has only a few fans.
 */
class SoundManager(context: Context) {

    /** Player's sound-FX slider level, 0..1; 0 mutes everything including the crowd. */
    @Volatile
    var volume: Float = 1f
        set(value) {
            field = value.coerceIn(0f, 1f)
            if (field <= 0f) stopLoops()
        }

    val enabled: Boolean get() = volume > 0f

    private val app = context.applicationContext
    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(20)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
        )
        .build()

    /** Sample ids that have finished decoding; loops wait for these before starting. */
    private val loaded = ConcurrentHashMap.newKeySet<Int>()

    init {
        pool.setOnLoadCompleteListener { _, id, status -> if (status == 0) loaded.add(id) }
    }

    private fun load(res: Int) = pool.load(app, res, 1)

    private val rng = Random(System.nanoTime())

    /** Several takes of one sound; next() never repeats the previous take. */
    private inner class Takes(vararg res: Int) {
        private val ids = IntArray(res.size) { load(res[it]) }
        private var last = -1

        fun next(): Int {
            val i = if (last < 0 || ids.size == 1) rng.nextInt(ids.size)
            else (last + 1 + rng.nextInt(ids.size - 1)) % ids.size
            last = i
            return ids[i]
        }
    }

    private val shots = Takes(R.raw.puck_hit, R.raw.puck_hit_2, R.raw.puck_hit_3)
    private val passes = Takes(R.raw.pass, R.raw.pass_2, R.raw.pass_3)
    private val boards = Takes(R.raw.wall_bounce, R.raw.wall_bounce_2, R.raw.wall_bounce_3)
    private val hits = Takes(R.raw.body_hit, R.raw.body_hit_2, R.raw.body_hit_3)
    private val saves = Takes(R.raw.save, R.raw.save_2)
    private val skates = Takes(R.raw.skate1, R.raw.skate2, R.raw.skate3, R.raw.skate4)
    private val pickupId = load(R.raw.pickup)
    private val faceoffId = load(R.raw.faceoff)
    private val postId = load(R.raw.post)
    private val whistleId = load(R.raw.whistle)
    private val hornId = load(R.raw.horn)
    private val cheerId = load(R.raw.cheer)
    private val organId = load(R.raw.organ_rally)
    private val jingleGoalId = load(R.raw.jingle_goal)
    private val jinglePeriodId = load(R.raw.jingle_period)
    private val jingleWinId = load(R.raw.jingle_win)
    private val jingleLoseId = load(R.raw.jingle_lose)
    private val clickId = load(R.raw.button_click)
    private val oneTimerId = load(R.raw.one_timer)
    private val gaspId = load(R.raw.gasp)
    private val penaltyId = load(R.raw.penalty)
    private val fireId = load(R.raw.fire)
    private val dekeId = load(R.raw.deke)
    private val glassId = load(R.raw.glass)
    private val padStackId = load(R.raw.pad_stack)
    private val tailBrightId = load(R.raw.tail_bright)
    private val tailDarkId = load(R.raw.tail_dark)
    private val murmurId = load(R.raw.crowd_loop)
    private val roarId = load(R.raw.crowd_roar)
    private val windId = load(R.raw.wind_loop)

    private val handler = Handler(Looper.getMainLooper())

    // Listener state, refreshed every frame by updateMix().
    @Volatile private var pan = 0f              // where the puck is, -1 left .. 1 right
    @Volatile private var puckSpeed = 0f
    @Volatile private var outdoor = false
    private var camX = 0f
    private var halfViewFt = 60f
    private var lastShotPower = 0.5f

    // Crowd excitement, 0 calm .. 1 bedlam. Events add to `boost`, which decays.
    private var excitement = 0f
    private var boost = 0f
    private var goalHold = 0f
    private var mixTimer = 0f

    // Ambience loops; guarded by `this` because pause/volume changes come from the UI thread.
    private var ambienceWanted = false
    private var loopsOutdoor = false
    private var murmurStream = 0
    private var roarStream = 0
    private var windStream = 0

    private fun gains(level: Float, pan: Float): Pair<Float, Float> {
        // Equal-power pan, normalised so a centred sound is full level on both sides.
        val a = (pan.coerceIn(-1f, 1f) + 1f) * (PI / 4).toFloat()
        val v = (level * volume).coerceIn(0f, 1f)
        return v * min(1f, cos(a) * SQRT2) to v * min(1f, sin(a) * SQRT2)
    }

    private fun play(id: Int, level: Float, rate: Float = 1f, priority: Int = 0, pan: Float = 0f) {
        if (!enabled) return
        val (l, r) = gains(level, pan)
        pool.play(id, l, r, priority, 0, rate.coerceIn(0.5f, 2f))
    }

    private fun later(delayMs: Long, block: () -> Unit) {
        handler.postDelayed({ if (enabled) block() }, delayMs)
    }

    private fun jitter(amount: Float) = 1f + (rng.nextFloat() * 2f - 1f) * amount

    private fun panFor(x: Float) = ((x - camX) / halfViewFt).coerceIn(-1f, 1f) * STEREO_WIDTH

    /** The arena's reverb after a big indoor impact; nothing bounces back outdoors. */
    private fun tail(bright: Boolean, level: Float) {
        if (outdoor) return
        play(if (bright) tailBrightId else tailDarkId, level, jitter(0.03f), 0, pan * 0.3f)
    }

    private fun bump(amount: Float) {
        boost = min(1.2f, boost + amount)
    }

    fun handle(event: GameEvent) {
        if (!enabled) return
        val pan = this.pan
        when (event) {
            GameEvent.SHOT -> {
                val power = ((puckSpeed - 55f) / 75f).coerceIn(0f, 1f)
                lastShotPower = power
                play(shots.next(), 0.8f + 0.2f * power, jitter(0.04f) * (0.97f + 0.06f * power), 1, pan)
                tail(true, 0.22f + 0.15f * power)
                bump(0.25f + 0.15f * power)
            }
            GameEvent.ONE_TIMER -> {
                lastShotPower = 1f
                play(oneTimerId, 1f, jitter(0.04f), 2, pan)
                tail(true, 0.45f)
                bump(0.4f)
            }
            GameEvent.PASS -> {
                val power = ((puckSpeed - 40f) / 40f).coerceIn(0f, 1f)
                play(passes.next(), 0.6f + 0.2f * power, jitter(0.06f), 0, pan)
            }
            GameEvent.PICKUP -> play(pickupId, 0.35f, jitter(0.12f), 0, pan)
            GameEvent.FACEOFF_DROP -> play(faceoffId, 0.8f, jitter(0.03f), 0, pan)
            GameEvent.BOARDS -> {
                // Soft taps along the boards stay soft; a hard rim booms and echoes.
                val k = (puckSpeed / 70f).coerceIn(0f, 1f)
                play(boards.next(), 0.5f + 0.4f * k, jitter(0.06f), 0, pan)
                if (k > 0.4f) tail(false, 0.22f * k)
            }
            GameEvent.POST -> {
                play(postId, 0.95f, jitter(0.02f), 1, pan)
                tail(true, 0.35f)
                bump(0.45f)
                later(120) { play(gaspId, if (outdoor) 0.4f else 0.85f, jitter(0.03f)) }
            }
            GameEvent.POKE -> play(passes.next(), 0.45f, 0.8f * jitter(0.05f), 0, pan)
            GameEvent.SAVE -> {
                play(saves.next(), 0.75f + 0.2f * lastShotPower, jitter(0.06f), 1, pan)
                tail(false, 0.12f)
                bump(0.2f)
                if (rng.nextFloat() < 0.3f) later(160) { play(gaspId, if (outdoor) 0.35f else 0.7f, jitter(0.03f)) }
            }
            GameEvent.HIT -> {
                play(hits.next(), 1f, jitter(0.06f), 1, pan)
                tail(false, 0.35f)
                bump(0.3f)
            }
            GameEvent.WHISTLE -> {
                play(whistleId, 0.9f, 1f, 2)
                tail(true, 0.18f)
            }
            GameEvent.PENALTY -> {
                play(penaltyId, 1f, 1f, 2)
                bump(0.2f)
            }
            GameEvent.HORN -> play(hornId, 1f, 1f, 2)
            GameEvent.GOAL -> {
                play(cheerId, if (outdoor) 0.45f else 1f, 1f, 2)
                goalHold = 3.5f
                bump(1f)
                later(700) { play(jingleGoalId, 0.9f, 1f, 2) }
            }
            GameEvent.PERIOD_END -> later(900) { play(jinglePeriodId, 0.85f, 1f, 2) }
            GameEvent.GAME_OVER -> {}   // the view calls playResult() with the outcome
            GameEvent.FACEOFF_SET ->
                if (!outdoor && rng.nextFloat() < 0.4f) later(250) { play(organId, 0.7f, 1f, 1) }
            GameEvent.ON_FIRE -> {
                play(fireId, 1.0f, 1f, 3)
                bump(0.3f)
            }
            GameEvent.DEKE -> {
                play(dekeId, 0.85f, jitter(0.08f), 1, pan)
                bump(0.1f)
            }
            GameEvent.GLASS_SHATTER -> {
                play(glassId, 1.0f, jitter(0.04f), 3, pan)
                tail(true, 0.45f)
                bump(0.6f)
            }
            GameEvent.GOALIE_SAVE_MOVE -> play(padStackId, 0.9f, jitter(0.06f), 2, pan)
        }
    }

    /**
     * Per-frame listener and crowd update: tracks the puck for panning and
     * shot strength, eases the crowd's excitement toward what's happening on
     * the ice, and every 50 ms pushes that into the ambience loops.
     */
    fun updateMix(w: World, cam: Camera, dt: Float) {
        val p = w.puck
        camX = cam.x
        halfViewFt = max(1f, cam.screenW / cam.scale / 2f)
        puckSpeed = p.speed
        // Mostly where the puck is on screen, plus a little of where it is on the rink,
        // so play near either net leans clearly to that side.
        pan = (((p.x - camX) / halfViewFt) * 0.8f + p.x / Rink.HALF_L * 0.2f).coerceIn(-1f, 1f) * STEREO_WIDTH
        outdoor = w.arenaType == ArenaType.WINTER_POND

        var target = when (w.phase) {
            Phase.PLAY -> 0.12f
            Phase.GOAL -> 1f
            else -> 0.05f
        }
        if (w.phase == Phase.PLAY) {
            // The crowd leans in as the puck gets deep, most of all in the slot.
            val depth = ((abs(p.x) - Rink.BLUE_LINE_X) / (Rink.GOAL_LINE_X - Rink.BLUE_LINE_X)).coerceIn(0f, 1f)
            val slot = 1f - (abs(p.y) / Rink.HALF_W).coerceIn(0f, 1f)
            target += 0.25f * depth * (0.5f + 0.5f * slot)
            val close = abs(w.teams[0].score - w.teams[1].score) <= 1
            if (close && (w.overtime || (w.period >= 3 && w.clock < 60f))) target += 0.15f
        }
        boost *= exp(-dt / 1.8f)
        if (goalHold > 0f) {
            goalHold -= dt
            target = 1f
        }
        target = min(1f, target + boost)
        val tau = if (target > excitement) 0.25f else 1.6f
        excitement += (target - excitement) * (1f - exp(-dt / tau))

        mixTimer -= dt
        if (mixTimer <= 0f) {
            mixTimer = 0.05f
            applyLoops()
        }
    }

    /** Starts, stops, swaps and levels the ambience loops to match the arena and the crowd's mood. */
    @Synchronized
    private fun applyLoops() {
        if (!ambienceWanted || !enabled) {
            stopLoops()
            return
        }
        if (outdoor != loopsOutdoor) {
            stopLoops()
            loopsOutdoor = outdoor
        }
        if (outdoor) {
            windStream = ensureLoop(windStream, windId)
            setLoopLevel(windStream, 0.55f, 0f)
        } else {
            murmurStream = ensureLoop(murmurStream, murmurId)
            roarStream = ensureLoop(roarStream, roarId)
            val e = excitement
            val s = ((e - 0.12f) / 0.88f).coerceIn(0f, 1f)
            setLoopLevel(murmurStream, 0.32f + 0.08f * e, 0f)
            // The roar leans a little toward the end the play is at.
            setLoopLevel(roarStream, s * s * (3f - 2f * s) * 0.75f, pan * 0.25f)
            if (roarStream != 0) pool.setRate(roarStream, 0.97f + 0.06f * e)
        }
    }

    private fun ensureLoop(stream: Int, id: Int): Int {
        if (stream != 0 || id !in loaded) return stream
        return pool.play(id, 0f, 0f, LOOP_PRIORITY, -1, 1f)
    }

    private fun setLoopLevel(stream: Int, level: Float, pan: Float) {
        if (stream == 0) return
        val (l, r) = gains(level, pan)
        pool.setVolume(stream, l, r)
    }

    @Synchronized
    private fun stopLoops() {
        for (s in intArrayOf(murmurStream, roarStream, windStream)) if (s != 0) pool.stop(s)
        murmurStream = 0
        roarStream = 0
        windStream = 0
    }

    /** Short skate scrape for a stride by the skater at world x. */
    fun playSkate(intensity: Float, x: Float) {
        val v = (0.12f + 0.3f * intensity).coerceIn(0.1f, 0.45f)
        play(skates.next(), v, jitter(0.06f), 0, panFor(x))
    }

    fun playResult(won: Boolean?) {
        when (won) {
            true -> play(jingleWinId, 0.95f, 1f, 2)
            false -> play(jingleLoseId, 0.9f, 1f, 2)
            null -> play(jinglePeriodId, 0.85f, 1f, 2)
        }
    }

    /** Asks for the crowd (or pond wind); it starts as soon as its samples have loaded. */
    @Synchronized
    fun startCrowd() {
        ambienceWanted = true
        applyLoops()
    }

    @Synchronized
    fun stopCrowd() {
        ambienceWanted = false
        stopLoops()
        excitement = 0f
        boost = 0f
        goalHold = 0f
    }

    fun playClick() = play(clickId, 0.6f)

    fun release() {
        handler.removeCallbacksAndMessages(null)
        stopCrowd()
        pool.release()
    }

    private companion object {
        const val SQRT2 = 1.4142135f
        const val STEREO_WIDTH = 0.75f
        const val LOOP_PRIORITY = 5
    }
}
