package com.tablehockey.game.game

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.os.Handler
import android.os.Looper
import com.tablehockey.game.R
import kotlin.random.Random

/**
 * All in-match effects: puck, boards, posts, hits, saves, whistle, horn,
 * crowd, skate scrapes, the arena organ and the 8-bit jingles. Every sample
 * is generated by tools/make_sounds.py.
 */
class SoundManager(context: Context) {

    /** Player's sound-FX slider level, 0..1; 0 mutes everything including the crowd. */
    @Volatile
    var volume: Float = 1f
        set(value) {
            field = value.coerceIn(0f, 1f)
            if (field <= 0f) stopCrowd()
        }

    val enabled: Boolean get() = volume > 0f

    private val app = context.applicationContext
    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(12)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
        )
        .build()

    private fun load(res: Int) = pool.load(app, res, 1)

    private val shotId = load(R.raw.puck_hit)
    private val passId = load(R.raw.pass)
    private val pickupId = load(R.raw.pickup)
    private val faceoffId = load(R.raw.faceoff)
    private val boardsId = load(R.raw.wall_bounce)
    private val postId = load(R.raw.post)
    private val hitId = load(R.raw.body_hit)
    private val saveId = load(R.raw.save)
    private val whistleId = load(R.raw.whistle)
    private val hornId = load(R.raw.horn)
    private val crowdId = load(R.raw.crowd_loop)
    private val cheerId = load(R.raw.cheer)
    private val skate1Id = load(R.raw.skate1)
    private val skate2Id = load(R.raw.skate2)
    private val organId = load(R.raw.organ_rally)
    private val jingleGoalId = load(R.raw.jingle_goal)
    private val jinglePeriodId = load(R.raw.jingle_period)
    private val jingleWinId = load(R.raw.jingle_win)
    private val jingleLoseId = load(R.raw.jingle_lose)
    private val clickId = load(R.raw.button_click)

    private val handler = Handler(Looper.getMainLooper())
    private val rng = Random(System.nanoTime())
    private var skateToggle = false
    private var crowdStream = 0

    private fun play(id: Int, level: Float, rate: Float = 1f, priority: Int = 0) {
        if (!enabled) return
        val v = (level * volume).coerceIn(0f, 1f)
        pool.play(id, v, v, priority, 0, rate)
    }

    private fun later(delayMs: Long, block: () -> Unit) {
        handler.postDelayed({ if (enabled) block() }, delayMs)
    }

    private fun jitter(amount: Float) = 1f + (rng.nextFloat() * 2f - 1f) * amount

    fun handle(event: GameEvent) {
        if (!enabled) return
        when (event) {
            GameEvent.SHOT -> play(shotId, 1f, jitter(0.08f), 1)
            GameEvent.PASS -> play(passId, 0.75f, jitter(0.1f))
            GameEvent.PICKUP -> play(pickupId, 0.35f, jitter(0.15f))
            GameEvent.FACEOFF_DROP -> play(faceoffId, 0.8f)
            GameEvent.BOARDS -> play(boardsId, 0.85f, jitter(0.12f))
            GameEvent.POST -> play(postId, 0.9f, 1f, 1)
            GameEvent.POKE -> play(passId, 0.5f, 0.8f)
            GameEvent.SAVE -> play(saveId, 0.9f, jitter(0.1f), 1)
            GameEvent.HIT -> play(hitId, 1f, jitter(0.1f), 1)
            GameEvent.WHISTLE -> play(whistleId, 0.9f, 1f, 2)
            GameEvent.HORN -> play(hornId, 1f, 1f, 2)
            GameEvent.GOAL -> {
                play(cheerId, 1f, 1f, 2)
                later(700) { play(jingleGoalId, 0.9f, 1f, 2) }
            }
            GameEvent.PERIOD_END -> later(900) { play(jinglePeriodId, 0.85f, 1f, 2) }
            GameEvent.GAME_OVER -> {}   // the view calls playResult() with the outcome
            GameEvent.FACEOFF_SET -> if (rng.nextFloat() < 0.4f) later(250) { play(organId, 0.7f, 1f, 1) }
        }
    }

    /** Short skate scrape; alternates two samples so strides don't sound identical. */
    fun playSkate(intensity: Float) {
        skateToggle = !skateToggle
        val id = if (skateToggle) skate1Id else skate2Id
        val v = (0.12f + 0.3f * intensity).coerceIn(0.1f, 0.45f)
        play(id, v, jitter(0.12f))
    }

    fun playResult(won: Boolean?) {
        when (won) {
            true -> play(jingleWinId, 0.95f, 1f, 2)
            false -> play(jingleLoseId, 0.9f, 1f, 2)
            null -> play(jinglePeriodId, 0.85f, 1f, 2)
        }
    }

    fun startCrowd() {
        if (!enabled || crowdStream != 0) return
        val v = 0.3f * volume
        crowdStream = pool.play(crowdId, v, v, 0, -1, 1f)
    }

    fun stopCrowd() {
        if (crowdStream != 0) {
            pool.stop(crowdStream)
            crowdStream = 0
        }
    }

    fun playClick() = play(clickId, 0.6f)

    fun release() {
        handler.removeCallbacksAndMessages(null)
        stopCrowd()
        pool.release()
    }
}
